server:
  port: 8180
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/ianRickmers/microservices-data-project
  application:
    name: config-service
